taskiq/abc/broker.py, taskiq/abc/result_backend.py
=> Taskiq result is now a generic model.

taskiq/brokers/inmemory_broker.py, taskiq/cli/async_task_runner.py
=> Added inmemory broker.

taskiq/__init__.py, taskiq/abc/broker.py, taskiq/abc/result_backend.py, taskiq/cli/async_task_runner.py, taskiq/decor.py, taskiq/kicker.py, taskiq/result.py, taskiq/task.py, taskiq/types_helpers.py
In this request I managed to split classes into separate files so it's easier to navigate across project.
=> Refactored code a little bit.

taskiq/cli/async_task_runner.py
=> Fixed worker process for windows.

.github/workflows/release.yml, .github/workflows/test.yml, poetry.lock, pyproject.toml, taskiq/brokers/inmemory_broker.py, taskiq/cli/args.py, taskiq/cli/async_task_runner.py, taskiq/cli/log_collector.py
This update adds publishing pipeline and fixes some issues with python3.7.
=> Package updated to be ready to be published on pypi.

.flake8, taskiq/abc/broker.py
=> Fixed name resolving for some cases.

poetry.lock, pyproject.toml, taskiq/cli/args.py, taskiq/cli/watcher.py, taskiq/cli/worker.py
This request add abillity to reload running workers on filesystem changes.
Closes #28.
=> Worker reloads on FS updates.

taskiq/cli/worker.py
At some point the reload process
could get invalid index error.
=> Fixed reload atomicity.

pyproject.toml
=> Description updated.

taskiq/middlewares/retry_middleware.py
Before this patch retry middleware
was updating actual taskiq message that were passed
to the broker.
=> Fixed message updates in retry middleware.

taskiq/brokers/inmemory_broker.py, taskiq/cli/receiver.py, taskiq/cli/tests/test_context.py, taskiq/context.py
=> Added context injector.

taskiq/formatters/json_formatter.py
=> Fixed message labels in json format.

docs/extending-taskiq/resutl-backend.md, taskiq/cli/worker/receiver.py, taskiq/cli/worker/run.py, taskiq/result.py
=> Fixed logging for multiprocessing, removed logs.

docs/available-components/brokers.md
=> Added docs for NATS broker

poetry.lock, pyproject.toml
Updated taskiq-dependencies package.
=> Updated taskiq-dependencies.

taskiq/cli/utils.py
=> Added exception info when cannot import tasks module

taskiq/cli/utils.py, taskiq/cli/watcher.py
=> Fixed windos fs-discover

poetry.lock, pyproject.toml
=> Removed importlib constraint

.flake8, taskiq/__main__.py, taskiq/abc/broker.py, taskiq/cli/utils.py, taskiq/cli/watcher.py, taskiq/cli/worker/args.py, taskiq/cli/worker/async_task_runner.py, taskiq/cli/worker/receiver.py, taskiq/cli/worker/run.py, taskiq/decor.py, taskiq/kicker.py, taskiq/task.py, taskiq/utils.py, tests/cli/worker/test_receiver.py
1. use semaphore, add test
2. change default max_async_tasks num
3. fix py39 has removesuffix
4. fix pre-commit
Please review it.
This PR will close #91.
=> asyncio.wait replaced with Semaphore, fixed compatibility issues

docs/examples/extending/broker.py, docs/extending-taskiq/broker.md, taskiq/abc/broker.py, taskiq/abc/formatter.py, taskiq/brokers/inmemory_broker.py, taskiq/brokers/shared_broker.py, taskiq/brokers/zmq_broker.py, taskiq/formatters/json_formatter.py, taskiq/receiver/receiver.py, tests/cli/worker/test_receiver.py
We changed the broker's interface once again. It's required to support multiple formats propperly. 
Now we're able to create MsgPack or pickle formatters.
=> Changed listen signature for brokers.

taskiq/middlewares/prometheus_middleware.py
This PR fixes prometheus middleware, so now it won't cause any problems running with multiple workers.
=> Fixed prometheus metrics for multiple worker processes

taskiq/cli/worker/run.py, taskiq/middlewares/prometheus_middleware.py
This PR adds description why some functions don't work. These errors have hints what dependencies should be installed to solve problems.
=> More verbose errors

taskiq/abc/broker.py
=> Added startup for result backends.

taskiq/cli/worker/args.py, taskiq/cli/worker/run.py
Hello there! I would like to let ppl use custom receiver if they need it.
=> feat: custom reciever

docs/guide/state-and-deps.md, taskiq/brokers/inmemory_broker.py, taskiq/cli/worker/args.py, taskiq/cli/worker/run.py, taskiq/receiver/receiver.py
This PR adds exception propagation to dependencies. Closes #139.
=> Exception propagation

docs/examples/extending/broker.py, docs/extending-taskiq/broker.md, taskiq/__init__.py, taskiq/abc/broker.py, taskiq/acks.py, taskiq/exceptions.py, taskiq/receiver/receiver.py, taskiq/utils.py, tests/receiver/test_receiver.py
Now you can easily add acknowledgements after message processing instead of acks right after messages was received.
=> Added acknowledgable messages.

taskiq/__init__.py, taskiq/__main__.py, tests/cli/worker/test_log_collector.py, tests/cli/worker/test_receiver.py, tests/test_state.py
=> feat: add package version

poetry.lock, taskiq/cli/worker/args.py, taskiq/cli/worker/run.py
This request adds parameter that disables automatic logging configuration for taskiq workers. 
This PR should solve #158.
=> Added optional logging configuration. 

docs/contrib.md, tox.ini
This PR adds guide of how to prepare everything for contribution.
=> Added contribution guides.

taskiq/compat.py, taskiq/serialization.py
Fixed deprecation warnings for pydantic.
=> Fixed deprecation warnings

taskiq/cli/scheduler/run.py
This issue solves problem from #170.
=> Fixed scheduler import. 

taskiq/abc/broker.py, taskiq/middlewares/prometheus_middleware.py
This PR fixes some issues with prometheus middleware and middlewares in general.
Referenece: #173.
=> Fixed prometheus middleware. 

taskiq/cli/scheduler/args.py, taskiq/cli/scheduler/run.py
=> Scheduluer CLI: Added optional logging config

docs/available-components/schedule-sources.md, docs/examples/state/async_generator_deps_annot.py, docs/examples/state/class_dependency_annot.py, docs/examples/state/dependencies_tree_annot.py, docs/examples/state/events_example_annot.py, docs/examples/state/generator_deps_annot.py, docs/examples/state/generics.py, docs/examples/state/generics_annot.py, docs/examples/state/no_cache_annot.py, docs/framework_integrations/taskiq-with-aiohttp.md, docs/framework_integrations/taskiq-with-fastapi.md, docs/guide/architecture-overview.md, docs/guide/scheduling-tasks.md, docs/guide/state-and-deps.md, docs/guide/testing-taskiq.md, package.json, pnpm-lock.yaml
Added information about `Annotated` type and timezones in scheduler.
=> Docs updated. 

taskiq/cli/scheduler/run.py
This PR adds shutdown calls for schedule sources. Previously this function wasn't called anywhere.
=> Added shutdown for schedule sources.

taskiq/serializers/__init__.py, taskiq/serializers/pickle.py, tests/serializers/test_serializers.py
Pickle can serializer any types and might be useful for systems where security is not a concern.
=> Added pickle serializer.

taskiq/acks.py, taskiq/api/receiver.py, taskiq/cli/worker/args.py, taskiq/cli/worker/run.py, taskiq/receiver/receiver.py
=> Added ack config.

docs/guide/cli.md
During my work on #244 I ran into some undocumented CLI options. I just added them to the docs.
=> Add missing CLI options documentation

docs/guide/cli.md, package.json, pnpm-lock.yaml
This PR updates docs dependencies and actually closes https://github.com/taskiq-python/taskiq/issues/311.
=> Updated docs.

poetry.lock, pyproject.toml, taskiq/exceptions.py
=> Fixed izulu exception annotations.

taskiq/api/scheduler.py, taskiq/cli/scheduler/args.py, taskiq/cli/scheduler/run.py, taskiq/schedule_sources/label_based.py, tests/cli/scheduler/test_task_delays.py, tests/cli/scheduler/test_updater.py, tests/schedule_sources/test_label_based.py, tests/scheduler/test_label_based_sched.py
This PR allows to configure for scheduler to run loop every n-seconds. It's useful for more precise task scheduling.
=> Added second-based scheduler intervals.
