README.md, poetry.lock, pyproject.toml, taskiq/__init__.py, taskiq/abc/broker.py, taskiq/brokers/zmq_broker.py, taskiq/cli/async_task_runner.py, taskiq/cli/worker.py
This pull request adds ZeroMQ broker.
Also it fixes signal handling for multiprocessing. Now we don't need to setup singnal handlers in child processes. It send `KeyboardInterrupt` exception. So we just catch it and create task to shut down the broker. Without any additional headache.
Also now you can use taskiq workers with uvloop. If uvloop is installed, taskiq applies uvloop policy to speedup message processing. 
Closes #24.
=> Added ZeroMQ broker, fixed multiprocessing.

taskiq/cli/async_task_runner.py, taskiq/context.py
Contexts can be used to extend taskiq's functionality within shared tasks. 
=> Added context.

taskiq/abc/broker.py, taskiq/brokers/inmemory_broker.py, taskiq/brokers/shared_broker.py, taskiq/brokers/zmq_broker.py, taskiq/cli/async_task_runner.py
=> Updated broker API.

.flake8, .github/workflows/test.yml, .gitignore, poetry.lock, pyproject.toml, taskiq/__init__.py, taskiq/funcs.py, taskiq/tests/conftest.py, taskiq/tests/test_funcs.py, taskiq/tests/test_stub.py
=> Added gather function.

taskiq/brokers/inmemory_broker.py, taskiq/cli/params_parser.py, taskiq/cli/receiver.py, taskiq/cli/tests/test_context.py, taskiq/cli/tests/test_parameters_parsing.py
This request fixes type resolving for python3.11+. Since in modern versions of python
all types are converted to strings. 
You can enable this by importing 
```
from __future__ import annotations
```
This request fixed logic how types are resolved.
=> Fixed parameter parsing for string annotations.

taskiq/abc/middleware.py, taskiq/cli/receiver.py
=> Added post-save hook in middlewares.

taskiq/cli/scheduler/args.py, taskiq/cli/scheduler/run.py
=> Fixed task pattern.

docs/examples/introduction/aio_pika_broker.py, docs/examples/introduction/full_example.py, docs/examples/introduction/inmemory_run.py, docs/examples/state/events_example.py, docs/guide/getting-started.md, docs/guide/scheduling-tasks.md, docs/guide/state-and-events.md, pyproject.toml, taskiq/__init__.py, taskiq/abc/broker.py, taskiq/abc/middleware.py, taskiq/abc/schedule_source.py, taskiq/brokers/inmemory_broker.py, taskiq/cli/worker/tests/test_receiver.py, taskiq/context.py, taskiq/decor.py, taskiq/events.py, taskiq/kicker.py, taskiq/scheduler/merge_functions.py, taskiq/scheduler/scheduler.py, taskiq/state.py, taskiq/task.py, taskiq/tests/test_state.py
=> Added events, state and event handlers.

taskiq/abc/broker.py, taskiq/abc/tests/test_broker.py
=> Added test for abstract broker.

taskiq/cli/worker/log_collector.py
=> Added ability to see redirected output.

.flake8, taskiq/cli/watcher.py, taskiq/cli/worker/args.py, taskiq/cli/worker/async_task_runner.py, taskiq/cli/worker/process_manager.py, taskiq/cli/worker/run.py
Refactored process management for workers. 
Now we use ublocking event queue and a big fat custom event loop.
It closes #63. Worker hanged, because observer thread was blocking on event queue until all events are processed. To solve this problem, I had to rewrite the whole process management logic from scratch.
=> Refaсtored process manager. 

.github/workflows/test.yml, taskiq/cli/worker/process_manager.py, taskiq/cli/worker/run.py
This PR removes Queue logging handler, so every process write to their own stdout. 
We might want to return QueueLogging pattern in the future, but it requires to implement our own domestic solution.
=> Removed Queue logging handler

LICENSE, docs/README.md, docs/guide/README.md
This request updates documentation. It adds info about current state of taskiq development and a comparison table for taskiq and other async task managers.
=> Added comparison table in docs

docs/guide/state-and-deps.md, taskiq/abc/broker.py, taskiq/cli/worker/receiver.py, tests/cli/worker/test_receiver.py
This feature allow lib developers to add new first-level dependencies for users. This will be used by `taskiq-fastapi` project.
=> Added ability to add custom first-level dependencies

taskiq/brokers/inmemory_broker.py, tests/brokers/test_inmemory.py
This PR makes inmemory broker more robust, because now we don't await for tasks to be executed, we execute them in a true async way.
=> Updated InMemoryBroker

taskiq/receiver/receiver.py, tests/cli/worker/test_receiver.py
This request fixes semaphore logic. 
Previously we had a case when tasks were created and they waited for semaphore to be released. This behavior can lead to OOM even if max_async_tasks number is small.
=> Fixed semaphore logic

taskiq/formatters/json_formatter.py, taskiq/message.py
bytes are more reliable than string. It would be easier to transfer objects which are not compatible with utf-8 using bytes.
=> Replaced string with bytes in BrokerMessage

docs/available-components/README.md, docs/available-components/middlewares.md, docs/extending-taskiq/README.md, pnpm-lock.yaml, poetry.lock, pyproject.toml, taskiq/__init__.py, taskiq/middlewares/prometheus_middleware.py, taskiq/receiver/receiver.py
This PR adds middleware that enables prometheus compatible metrics.
=> Added prometheus metrics middleware.

docs/guide/cli.md, poetry.lock, pyproject.toml, taskiq/__main__.py, taskiq/cli/worker/args.py, taskiq/cli/worker/process_manager.py, taskiq/cli/worker/run.py
This PR makes watchdog and gitignore parser dependencies optional. Now if you install taskiq it won't install reload packages by default. It makes it smaller for production use. Because these dependencies are only required for development.
=> Reload dependencies are now optional.

taskiq/receiver/receiver.py
When using the memory broker, because the task is executed quickly, the execution time becomes scientific notation, so I think it is enough to keep 2 decimal places
=> fix: execution time retains 2 digits

taskiq/cli/worker/args.py, taskiq/cli/worker/run.py, taskiq/receiver/receiver.py
`max_prefetch` argument for receiver
In Celery there are `worker_prefetch_multiplier`
Very useful in some cases
=> feat: receiver max_prefetch argument

docs/available-components/brokers.md, docs/examples/extending/result_backend.py, docs/guide/architecture-overview.md, docs/guide/scheduling-tasks.md, docs/guide/state-and-deps.md, docs/guide/taskiq-with-fastapi.md, docs/guide/testing-taskiq.md, taskiq/abc/broker.py, taskiq/abc/middleware.py, taskiq/abc/result_backend.py, taskiq/brokers/inmemory_broker.py, taskiq/cli/scheduler/args.py, taskiq/cli/scheduler/run.py, taskiq/cli/watcher.py, taskiq/cli/worker/args.py, taskiq/cli/worker/log_collector.py, taskiq/cli/worker/process_manager.py, taskiq/cli/worker/run.py, taskiq/decor.py, taskiq/events.py, taskiq/message.py, taskiq/receiver/params_parser.py, taskiq/receiver/receiver.py, taskiq/schedule_sources/label_based.py, taskiq/task.py, tests/cli/worker/test_receiver.py, tests/middlewares/test_simple_retry.py, tests/test_funcs.py
While looking at the docs, I found that the commands 
```
taskiq test_project.broker:broker test_projec.submodule.tasks test_projec.utils.tasks
```
```
taskiq test_project.broker:broker -fsd
```
were missing the `worker` argument.
While fixing it, I also fixed some obvious typos.
=> Fix typos and command in docs

taskiq/exceptions.py, taskiq/receiver/receiver.py, tests/cli/worker/test_receiver.py
if user doesn't want to set result he can raise `NoResultError`
=> feat: no result error

taskiq/abc/broker.py, taskiq/cli/scheduler/run.py
This commit adds flag that shows in which environment broker is running
currently.
It's required to fix tasks discovery for projects that use framework
integrations and do not import tasks directly. Closes #142.
=> Added scheduler flag.

taskiq/__init__.py, taskiq/acks.py, taskiq/context.py, taskiq/exceptions.py, taskiq/receiver/receiver.py, tests/receiver/test_receiver.py, tests/test_requeue.py
Added requeue method for context to solve problems in scenario described in #132.
=> Added context methods to reject and requeue. 

.flake8, taskiq/abc/broker.py, taskiq/receiver/receiver.py, tests/conftest.py, tests/test_requeue.py
Now you can easily throw exception from dependencies and that will stop task execution and safely return you an error. 
Also it should be useful for scenario described in #132.
=> Added exception catches from dependencies.

taskiq/context.py, tests/test_requeue.py
It seems that there is no need to copy here, If you need to regenerate a message object here you should use deepcopy.
=> fix: requeue message

taskiq/cli/worker/process_manager.py, taskiq/cli/worker/run.py
issues: https://github.com/taskiq-python/taskiq/issues/63 https://github.com/taskiq-python/taskiq/pull/81
child process inherits signal handlers from parent
the problem is that the `terminate` signal was triggered before the signal handler of the child process was set, we must set it immediately after the process starts
and I suggest telling the parent process that the worker is ready before the parent continues with the event queue.
or at least wait a while for the worker process to set the signal handler
or we can handle it in parent signal handler, and raise an error if it is not a main process
=> fix: worker hangs sometimes

docs/examples/extending/middleware_async.py, docs/examples/extending/middleware_sync.py, taskiq/abc/broker.py, taskiq/abc/middleware.py, taskiq/brokers/zmq_broker.py, taskiq/cli/scheduler/run.py, taskiq/cli/worker/run.py, taskiq/middlewares/prometheus_middleware.py, tests/conftest.py
Now we set `is_worker_process` to only those brokers which are actually workers right now. 
Along with that I had to add `startup` and `shutdown` methods to middlewares.
This PR references discussion #161.
=> Added better support for multi-broker setup.

poetry.lock, pyproject.toml
This dependency is used in for pydantic compatibility. It appears in tests, but it doesn't exist in raw installation.
=> Added missing dependency.

taskiq/cli/worker/run.py
Calling `Process.start()` on MacOS or Windows generate this issue:
```
poetry run taskiq worker escalidrawapi.broker:broker
[2023-07-17 17:06:29,035][taskiq.worker][INFO   ][MainProcess] Starting 2 worker processes.
[2023-07-17 17:06:29,040][taskiq.process-manager][INFO   ][MainProcess] Started process worker-0 with pid 23418 
[2023-07-17 17:06:29,042][taskiq.process-manager][INFO   ][MainProcess] Started process worker-1 with pid 23419 
Traceback (most recent call last):
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/Users/thoas/.pyenv/versions/3.11.2/lib/python3.11/multiprocessing/spawn.py", line 120, in spawn_main
File "<string>", line 1, in <module>
File "/Users/thoas/.pyenv/versions/3.11.2/lib/python3.11/multiprocessing/spawn.py", line 120, in …
```
=> fix: multiprocessing start method on darwin platform

docs/guide/getting-started.md, taskiq/receiver/receiver.py, tests/receiver/test_receiver.py
=> Added timeouts.

poetry.lock, pyproject.toml, taskiq/cli/scheduler/run.py, taskiq/schedule_sources/label_based.py, taskiq/scheduler/scheduler.py, tests/cli/scheduler/test_is_now.py
This PR adds timezones to schedules. You can specify timezone for `cron` using new `cron_offset`. It accepts either timezone name or timedelta offset. 
Also, now every time you get a task with specific time, timezone is applied. For backward compatibility, if time has no timezone, we assume that it's in UTC.
=> Added timezone-aware schedule support.

taskiq/cli/scheduler/run.py, tests/cli/scheduler/test_task_delays.py
This PR fixes how scheduler treats specific time. Now if you scheduler a task with time attribute, it will be sent almost exactly on time +-1 second. 
=> Fixed delay for specific time values.

taskiq/abc/broker.py, taskiq/brokers/inmemory_broker.py, taskiq/brokers/shared_broker.py, taskiq/cli/worker/run.py, taskiq/receiver/receiver.py, taskiq/schedule_sources/label_based.py, tests/conftest.py, tox.ini
As discussed with @dtatarkin in #202 we need to have a difference between tasks registered by user and shared, that were created using `async_shared_broker`.
=> Added local task registry, improved shared_tasks API. 

taskiq/abc/broker.py
Now instead of using decorator generator, users can easily register their tasks programmatically using new `register_task` function.
=> Added API for registering tasks programmatically. 

docs/examples/dynamics/receiver.py, docs/examples/dynamics/scheduler.py, docs/guide/dynamic-brokers.md
I think after these changes, the article is somewhat easier to read. There are still some rough edges, but we can focus on them later.
I can go through the docs and fix everything that I can find, but it'll take some time, so let's start with some smaller changes first.
=> Make  `dynamic-brokers.md` easier to read

.github/workflows/test.yml, docs/guide/message-format.md, poetry.lock, pyproject.toml, taskiq/abc/broker.py, taskiq/serializers/__init__.py, taskiq/serializers/cbor_serializer.py, taskiq/serializers/msgpack_serializer.py, taskiq/serializers/orjson_serializer.py, tests/cli/scheduler/test_task_delays.py, tests/serializers/test_serializers.py
This PR adds new serializers that can be used with taskiq. 
Serializers allow users to choose how messages are going to be formatted when sent to broker.
This PR adds 3 serializers:
* ORJSONSerializer - faster json implementation, based on [orjson](https://pypi.org/project/orjson/) lib.
* MSGPackSerializer - [msgpack](https://pypi.org/project/msgpack/) protocol implementation.
* CBORSerializer - [cbor](https://pypi.org/project/cbor2/) protocol implementation
=> Added new serializers.

docs/examples/extending/schedule_source.py, taskiq/abc/schedule_source.py, taskiq/cli/scheduler/run.py, taskiq/schedule_sources/label_based.py, taskiq/scheduler/merge_functions.py, taskiq/scheduler/scheduler.py, tests/cli/scheduler/test_task_delays.py, tests/schedule_sources/test_label_based.py, tests/scheduler/test_label_based_sched.py
The `source` field in the `TaskiqSchedule` class seemed to be redundant for me. It was adding unnecessary complexity for the extensions API. This change is incompatible with the previous version. 
=> Removed source from the TaskiqSchedule.

taskiq/cli/scheduler/run.py
This issue targets [hisenbug](https://textual.textualize.io/blog/2023/02/11/the-heisenbug-lurking-in-your-async-code/) of asycio. In most cases is should not be a problem and taskiq haven't received any related issues yet. But it might be problematic.
=> Now running tasks are stored in memory.

taskiq/receiver/receiver.py
This PR fixes the acknowledgements behavior. If worker goes down when executing tasks, message won't be acknowledged untill it executed.
=> Fixed when messages are acked.

.github/workflows/test.yml
This PR adds test runs on develop and mater branches because it needs to send info to codecov in order to correctly calculate diffs in coverage.
=> Fixed codecov delta calculations for PRs.

taskiq/cli/scheduler/run.py, taskiq/scheduler/scheduler.py, tests/cli/scheduler/test_updater.py
Now scheduler doesn't run periodic update task in the background. Now it runs it every minute when scheduler runs.
This simplifies both the scheduling API and makes the scheduler less error-prone.
=> Simplified scheduler.

.github/workflows/test.yml, pyproject.toml, taskiq/cli/worker/run.py
Reverts taskiq-python/taskiq#224
=> Lint fixes.

docs/examples/extending/schedule_source.py, docs/extending-taskiq/schedule-sources.md, taskiq/abc/schedule_source.py, taskiq/decor.py, taskiq/kicker.py, taskiq/scheduler/created_schedule.py, taskiq/scheduler/scheduled_task.py, tests/schedule_sources/test_label_based.py, tests/scheduler/test_label_based_sched.py
This PR adds new abstraction called "CreatedSchedule". When `schedule_*` methods are called, the `CreatedSchedule` is returned. This class has methods to unschedule previously scheduled tasks.
Also, we added new method to the schedule source to remove schedules. To make this method easy to implement, we had to once again add new field `schedule_id` to the `ScheduledTask`. To make it backward compatible though, we made it with default_factory.
=> Added unschedule possibility.

pyproject.toml, taskiq/abc/broker.py, taskiq/receiver/receiver.py
This PR adds aability to override dependency functions. This functionality is kinda similar to how fastapi handles dependency overrides dict. Useful for testing purposes.
=> Added depdencies override as in fastapi.

taskiq/cli/worker/run.py
This PR sets loop event loop explicitly. Because there are cases, when this might become a problem. 
Ref: #229
=> Set event loop for current thread explicltly.

docs/examples/extending/schedule_source.py, taskiq/abc/schedule_source.py, taskiq/exceptions.py, taskiq/scheduler/scheduler.py, tests/scheduler/test_scheduler.py
Followup to #244.
This PR implements a new exception `ScheduledTaskCancelledError` which can be raised in `ScheduleSource.pre_send` method.
This exception is then caught and processed in `TaskiqScheduler.on_ready`. This way, schedule source can decide upon invocation whether the task should be actually performed or not.
=> Add scheduler pre_send exception handling

docs/guide/cli.md, taskiq/cli/scheduler/args.py, taskiq/cli/utils.py, taskiq/cli/worker/args.py, tests/cli/test_utils.py
Closes #256.
As per #256, i changed the `rglob` pattern search to `glob` and added a possibility to specify `--tasks-pattern` option multiple times.
=> Update task patterns

taskiq/cli/worker/run.py
Should help fix a similar problem to #229, but in the case of using uvloop.
I caught this problem on python3.8 with uvloop.
=> Set uvloop for current thread explicitly.

taskiq/cli/worker/process_manager.py, taskiq/cli/worker/run.py
Removed startup event so we can use spawn multiprocessing model instead of fork. Because MacOS's security policies break forking.
=> Removed startup event.

taskiq/compat.py
=> feat: reuse pydantic v2 TypeAdapter instance

taskiq/cli/worker/args.py, taskiq/cli/worker/run.py, taskiq/receiver/receiver.py
Closes https://github.com/taskiq-python/taskiq/issues/309.
=> Added max-tasks-per-child parameter.

taskiq/api/receiver.py, taskiq/receiver/receiver.py
Closes https://github.com/taskiq-python/taskiq/issues/313
=> Fixed receiver's `run_startup` parameter typo.

docs/framework_integrations/taskiq-with-aiogram.md, taskiq/cli/scheduler/run.py
Fixed a bug that causes second execution of task in a same minute
=> Avoid duplication of task execution

docs/guide/scheduling-tasks.md, taskiq/cli/scheduler/run.py, taskiq/scheduler/scheduler.py
=> Added schedule_id label to the task.

docs/guide/cli.md, taskiq/cli/worker/process_manager.py, taskiq/cli/worker/run.py
This PR adds graceful reload signal handler. Closes #325.
=> Added graceful reload on SIGHUP.

docs/guide/cli.md, taskiq/cli/worker/process_manager.py
This PR fixes https://github.com/taskiq-python/taskiq/issues/333.
=> Removed SIGHUP handler on win32.

.github/workflows/release.yml, pyproject.toml, taskiq/scheduler/created_schedule.py
Taskiq has switched to github flow instead of git flow that was previously used, because it's just much simpler and faster to release features that way.
=>  Changed package to be github-flow compatible.

taskiq/cli/worker/process_manager.py, taskiq/receiver/receiver.py
Without this change, I found that workers could get stuck on a long-running task. Worker processes are sent a SIGINT, and then that signal is handled appropriately to exit the prefetcher & runner.
Is this appropriate as general purpose behaviour, and if not, would it make sense as a command-line option?
=> fix: SIGINT worker processes when process_manager starts

taskiq/abc/broker.py
Hi,
Thank you for creating this awesome package!
I have spotted a potential typo issue that stops our shutdown middleware hook from working properly.
I have thought that perhaps I could add some tests, but I've then decided to make it in another PR just to reduce some of my work.
Please feel free to comment, and let me know in case you prefer to have tests for this PR.
=> Fix shutdown middleware hook

.github/workflows/release.yml, .github/workflows/release_docs.yaml
Now it's not required to make a release to release docs.
=> Added separate workflow for docs.

taskiq/brokers/zmq_broker.py
Fixes https://github.com/taskiq-python/taskiq/issues/378.
=> Fixed wrong host for ZMQ broker.

docs/guide/testing-taskiq.md, taskiq/brokers/inmemory_broker.py, tests/brokers/test_inmemory.py
Since InMemoryBroker is used mostly for testing purposes, it would be pretty convenient to add some methods that will help in testing software.
=> Added utilities method for inmemory broker.

taskiq/labels.py
=> Enhance boolean label handling

taskiq/cli/scheduler/run.py, tests/cli/scheduler/test_task_delays.py
When using the `.schedule_by_time()` method, I encountered a problem where the task starts more than 1 second earlier than the scheduled time. I believe the scheduler should not start tasks before the specified time.
This PR fixes this issue. Also added a test that simulates my problem.
=> Fix task delay for specific time with milliseconds

taskiq/cli/utils.py, tests/cli/test_utils.py
I used Cython to compile the .py files into .so files. However, taskiq can only automatically discover .py files, so I added support for .pyc, .pyd, and .so files.
=> support discovering pyc/pyd/so modules

taskiq/cli/worker/run.py
This PR fixes the way shutdowns are being invoked.
The behavior before this change was correct in previous versions of the shutdown logic. However, I updated the way shutdown events are propagated in #381, and since then, the broker has stopped propagating the `KeyboardInterrupt` exception. As a result, the shutdown() method was not being called.
Fun observation, the hard-kill logic still throws a `KeyboardInterrupt` exception, and if the hard-kill is triggered quickly enough, the shutdown will occur correctly.
Fixes #424.
=> Fixed shutdowns.

taskiq/decor.py, taskiq/kicker.py, taskiq/serialization.py, taskiq/task.py
This PR removes a non-existent parameter from the docstring and fixes spelling errors within it.
=> Fix docstring: remove non-existent parameter and correct typos

taskiq/result_backends/dummy.py, taskiq/task.py
=> Warn if result backend is unset

README.md, docs/README.md, docs/available-components/schedule-sources.md, docs/framework_integrations/faststream.md, docs/framework_integrations/taskiq-with-aiogram.md, docs/framework_integrations/taskiq-with-fastapi.md, docs/guide/cli.md, docs/guide/scheduling-tasks.md, docs/guide/testing-taskiq.md, taskiq/abc/broker.py, taskiq/brokers/inmemory_broker.py, taskiq/cli/scheduler/run.py, taskiq/cli/watcher.py, taskiq/cli/worker/run.py, taskiq/context.py, taskiq/exceptions.py, taskiq/funcs.py, taskiq/receiver/receiver.py, taskiq/result_backends/dummy.py, taskiq/schedule_sources/label_based.py, tests/cli/test_utils.py, tests/receiver/test_receiver.py, tests/scheduler/test_scheduled_task.py
Hi all, thanks for making this repo; it's really useful.
This PR fixes some typos and also adds a warning when a scheduled task's broker doesn't match the broker it's being executed on. This has fucked me over several times when scheduled tasks are registered but silently fail to execute. This was my own fault since I was double-registering tasks. But it's a nasty pitfall.
Should we detect mismatched brokers a bit sooner, i.e. when the task is first registered? Probably if a user tries to register a function that's already an instance of a decorated task, we should throw an error if the brokers don't match.
=> Fix Typos, Warn on Unmatching Brokers

taskiq/cli/worker/args.py, taskiq/cli/worker/run.py
**Technical explanation of the issue:**
1. When using 'fork', a copy of the current process is created, including memory and state of all objects. This means logging settings are preserved.
2. When using 'spawn', a new process is created which imports modules fresh. This means all global objects, including loggers, are initialized again.
**Problem in taskiq code:**
1. Logging configuration happens in the parent process, but these settings are not passed to child processes when using 'spawn'.
2. DEBUG logs are not visible because by default loggers in child processes have WARNING or INFO level.
**PR fixes:**
1. This PR fixes the logging issue when using the 'spawn' method in multiprocessing
2. Adds log-format support, which allows more flexible configuration of logger behavior when using …
=> fix: log configuring when running under spawn and add --log-format

taskiq/abc/broker.py, taskiq/brokers/shared_broker.py, taskiq/compat.py, taskiq/decor.py, taskiq/kicker.py, taskiq/task.py, tests/test_task.py
This patch adds result parsing when got serialized result from result backend. It requires type annotation for that. Parsing is laxed and if failed, result will be returned as is. 
Referenced issue: https://github.com/taskiq-python/taskiq-redis/issues/75
@jegork, this issues appears much deeper into core than I initially thought. Fixing it breaks some backward compatibility.
=> Added result parsing on return.

taskiq/cli/watcher.py, taskiq/cli/worker/args.py, taskiq/cli/worker/process_manager.py
This is a small change that partially addresses #318, and allows multiple reload dirs to be specified via the CLI instead of using just the CWD, using the `--reload-dir` option, which can be passed multiple times for multiple reload directories.
Why I need this:
I use TaskIQ with tasks loaded from pip packages that I've installed with `pip install -e path/to/local/package` in development, and am constantly editing and having to manually reload TaskIQ due to the fact that the locally-installed package is outside of the CWD.
- If the --reload-dir option is not passed, the default of using the CWD is still used.
- pytest tests still pass
- Committed with pre-commit hooks installed and working
- Adds a logger.debug of the reload dirs being watched.
=> Add --reload-dir argument

taskiq/kicker.py, taskiq/scheduler/scheduled_task/v1.py, taskiq/scheduler/scheduled_task/v2.py, taskiq/scheduler/scheduler.py, tests/test_retry_task.py
https://github.com/taskiq-python/taskiq/issues/493
Fixed an issue where task_id was changing on task retries when using retry middlewares.
add: task_id for retry scheduled task
=> BUG FIX:  issue:493 Loss of task_id when using retry middlewares
